// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChvDUfsvt0tG5Jaf8tdajS7kWT9BFXn8o',
    appId: '1:691959809611:web:ca1daceb455e9e75732fce',
    messagingSenderId: '691959809611',
    projectId: 'for-exercise',
    authDomain: 'for-exercise.firebaseapp.com',
    databaseURL: 'https://for-exercise-default-rtdb.firebaseio.com',
    storageBucket: 'for-exercise.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvqOulA-6ve0YLkKmKawmNEpzOcCJYRWs',
    appId: '1:691959809611:android:4eb7fb00baab79e1732fce',
    messagingSenderId: '691959809611',
    projectId: 'for-exercise',
    databaseURL: 'https://for-exercise-default-rtdb.firebaseio.com',
    storageBucket: 'for-exercise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1CmldiivQth-uNehAg-2QDooZHB3mEdU',
    appId: '1:691959809611:ios:58461b986a4b6ce9732fce',
    messagingSenderId: '691959809611',
    projectId: 'for-exercise',
    databaseURL: 'https://for-exercise-default-rtdb.firebaseio.com',
    storageBucket: 'for-exercise.appspot.com',
    iosBundleId: 'com.example.githubTmdb',
  );
}
